theme = "slick"
icons = "awesome"

[[block]]
block = "music"
#max_width = 21
#marquee = true
format = "{artist}[sep]{title}"
buttons = ["play", "next"]
player = "org.mpris.MediaPlayer2.playerctld"

[[block]]
block = "pacman"
interval = 100
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "trizen -Qua"

#[[block]]
#block = "custom"
#command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
#interval = 600

#[[block]]
#block = "focused_window"
#max_width = 21

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0 


#[[block]]
#block = "net"
#device = "wlan0"
#format = "{ssid} {signal_strength}"
#{ip} {speed_down;K*b} {graph_down:8;M*_b#50}"
#interval = 5

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
format = "$time"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"


#[[block]]
#block = "custom"
#command = "uname -r"
#interval = "once"

#[[block]]
#block = "custom"
#command = "xrandr --listmonitors | tail -n+2 | tr '+' ' ' | cut -d' ' -f 4 | tr '\n' ' '"
#interval = "once"
#signal = 4

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/{{ .getmail }}/personal", "{{ .maildir}}/personal/inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"