#!/bin/bash


function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevolume"  -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

pamixer -u
pamixer -d 5 --allow-boost
send_notification down

